### ISSUE TITLE
Set top problem

### ISSUE THREAD

**Issue by Mystqr4** [WindowTop/WindowTop-App#314]
I have noticed with the latest version if I have a window (Lets call it W1) set to PiP and take off always on top it will go to the background which is great so I can focus on my browser (Lets call it W2) without it in the way again on top but if I open another window Lets call it W3) or application and then focus the browser (W2) again which naturally would put it over the top of everything and of course and anchor will appear for W3 if I right click on that to dismiss it W1 will appear again and stay on top for no apparent reason whilst not having the "set top" feature active/in use. 
The only way to then fix it to go back to the background under W2 is to click the "set top" option again twice to enable and then disable it.

Odd! I'm not sure of this is working as intended or something in the settings but I find it to be odd behaviour.

**Comment by Mystqr4** [comment]
Update:
It also happens if I bring that unrelated anchor window to focus.

**Comment by gileli121** [comment]
@Mystqr4 
Thank you for the report.
I will check it during the week when I get the time.

**Comment by gileli121** [comment]
@Mystqr4 
Very strange bug
I was able to reproduce it.

Very interesting scenario.

Thank you.

Btw, do you want the feature to have minimize and close buttons here:
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/3fef647b-8b4f-4e11-ab5a-ed8bbe7e53e3)

I am surprised that it was not requested yet.
I see it as quite useful.
I think that it should show the window on the taskbar here 
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/5c2fc9bb-08bf-4ba9-96fa-02d5a504f774)

BUT only when the PIP is minimized.
And I suggest to make it show like this:

![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/343f9b9b-a74b-4415-869d-24ec526542b6)


So, if it is from PIP, it will show on the taskbar with the PIP icon.

If it is only crop (this is developed now - see https://github.com/WindowTop/WindowTop-App/issues/313 for more info), it will show this:
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/90574254-ca97-41f8-bb78-47147cc020a2)


If you un-miminze it, the icon will disappear **if the PIP is always-on-top** (otherwise it will still show)

Let me know what you think.

**Comment by Mystqr4** [comment]
I don't know when this bug crept into things because I don't recall it ever being a problem before so perhaps over the last two versions maybe.

Wow! 
That's some great ideas!
I wonder how the minimize and close buttons would scale on the tab when the PiP is at its smallest size. Would it be a problem?

I would definitely like to see this and am also surprised it has not be requested yet. Seems like a natural step in the evolution here without being over the top. Excellent!

**Comment by gileli121** [comment]
@Mystqr4 
Great, I will work on it one day.
For now, about this bug - I am fixing it and also making some improvement here with the anchor icons
I will send screenshot later

**Comment by gileli121** [comment]
@Mystqr4 
See this beta release and let me know how it works and what you think about the Anchors improvements and other improvements. 

https://github.com/WindowTop/WindowTop-App/releases/tag/v5.22.0

Thank you.

**Comment by Mystqr4** [comment]
The good news is that you fixed the bug. The new features appear to be pretty good. I did however have one problem when I have a window in 'PiP mode' without 'Set top' mode active and behind a fullscreen window. The anchor appears as per normal however when try to hide the anchors via right click it also takes it out of PiP mode but and the anchor disappears but then it also leaves behind a weird condensed title bar which sometimes sits above the windows start menu taskbar button in the bottom left the weird little title bar has the "restore up, Maximize and close" button on it.

![pPvvAWZXU1](https://github.com/WindowTop/WindowTop-App/assets/65718578/c395a109-5a7b-45dd-9237-00223ba44c8c)

**Comment by gileli121** [comment]
@Mystqr4 
I was unable to reproduce this bug.
Maybe because somehow it is fixed now.

During the last two days, I have worked hard on improving the feature https://github.com/WindowTop/WindowTop-App/issues/313 
and during the same time, I also fixed and adjusted some core logic in the app.

Can you please try Beta 3 from here?
https://github.com/WindowTop/WindowTop-App/releases/tag/v5.22.0 

I just uploaded it now.

**Comment by gileli121** [comment]
@Mystqr4 
Please check Beta 4. I just uploaded it.
Fix for https://github.com/WindowTop/WindowTop-App/issues/313#issuecomment-1703967189

**Comment by Mystqr4** [comment]
The Live Preview feature looks great.

It's still happening here. I might have to test a few things on my end since we don't have anyone else experiencing the same thing or testing it right now.

**Comment by gileli121** [comment]
@Mystqr4 
I was unable to reproduce the issue.
I also tried Notepad.
From your screenshot, it looks like you are using Windows 10.
Am I right? 

I am using Windows 11. Maybe it is related to Notepad on Windows 10.

Can you check if you got the issue using the last stable release? ( download from here: https://github.com/WindowTop/WindowTop-App/releases/tag/v5.21.2 )

I need to know if it started after this feature update.

In addition, please attach your settings.json file which can be found here in `%appdata/windowtop`


![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/b2d3f936-0318-440b-9574-a5356da3028b)

Before you do it, please remove the activation (if you have one) by going to the activation page and clicking "Deactivate"

![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/52b7e155-57db-4b3a-86ba-13a5d0416456)

![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/cc497bcd-3ad4-49c3-b85e-7e08aea75b5d)

You can make a copy of `settings.json` with the activation included.


Maybe something in your settings.json may explain it, and I want to try reproducing it using it.
I hope not to try installing a Windows 10 VM to reproduce it.


Thanks.

**Comment by Mystqr4** [comment]
I am running Windows 10 pro.

Reinstalling 5.21.2 brings back the old bug that we started with that you managed to fix in subsequent releases however I have noticed that on the last new versions beyond this it will show me an anchor when I put for example notepad in PiP mode and disable/unclick "Set top" mode so the PiP should fall to the background. In the old version no anchors appear in PiP mode when I do that but on the new versions anchors do appear. 

I've gone back to the new beta version and it happens with WinRAR, Notepad, FreeTube, Irfanview, DownZemAll, MPC-HC (64-bit) by clsid2 and Game Scanner of the few I have tested it with.

I tried restarting multiple times.

I have made a backup of my settings.json file for myself and have now deactivated WindowTop and uploaded the settings.json file here. (I gladly paid for this software some time ago now)

[settings.zip](https://github.com/WindowTop/WindowTop-App/files/12526209/settings.zip)

I hope it helps and you don't have to install windows 10 on a VM to find out.

This is some of the best customer service I have had. I recently put together some money to buy another unrelated software even though I am in a tight financial space and had a problem with it. I got 2-3 replies but then after that nothing. I feel cheated from them especially since part of the license stipulation is that you get support for x amount of time and then have to also renew your license after x amount of time. Stuck with half working software, less money and no solution.

This goes to show that WindowTop is worth spending your money on. Excellent support.

**Comment by gileli121** [comment]
@Mystqr4 
Thank you for the feedback. Great to hear.
I will look into it later today.
Yesterday, I was working on this https://github.com/WindowTop/WindowTop-App/issues/313#issuecomment-1707350313

**Comment by Mystqr4** [comment]
Tried doing a few windows 10 updates. (The garbage Microsoft pushes is unreal!) and WindowTop is still doing the same thing.

**Comment by gileli121** [comment]
@Mystqr4 
I haven't had time yet to investigate the bug.
During testing beta 5, I found and solved a lot of issues that found during testing.

I hope to return to it when I finish all the other bugs.

This is why users usually don't complain about big issues when I release a stable release.

**Comment by gileli121** [comment]
@Mystqr4 
Thanks.
The issue was reproduced on my side using WinRAR

![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/6fd78a4e-ac7d-4dce-b8a2-2763c4c551bd)

**Comment by gileli121** [comment]
The same issue can also be reproduced if you minimize the window via PIP mode by right-clicking the context menu from the toolbar
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/ae961488-a630-4f22-a01e-d6bbbdf1b551)

The Anchor just uses the same logic inside the PIP class and something there is not doing the right job.

**Comment by gileli121** [comment]
@Mystqr4 
It fixed.
Please try beta 6 from here:

https://github.com/WindowTop/WindowTop-App/issues/313#issuecomment-1712645441

Please let me know if it is fixed for you.
Thanks.

**Comment by gileli121** [comment]
@Mystqr4 

I found a regression from beta 6 using your configuration.. the app failed to start as an admin user if it was configured to start as an admin user.

It is fixed in beta 7.

Download from here

https://github.com/WindowTop/WindowTop-App/issues/313#issuecomment-1712663166

**Comment by gileli121** [comment]
Thanks.
There is progress indeed.
It is the first time in 5.22 that I did not find bugs after 5-10 minutes of using it.
I reproduced one bug today: some anchor icons still appeared even when its window was not covered.
It was a one-time event from 9-10 hours of working on daily stuff at work.
But even this one-time event never happened on 5.21

I suspect that I know what caused it.
The changes in 5.22 are huge. The fight against bugs is extremely tough. 
Beta 5 was the most unstable. Beta 8 seems to be close to what I may consider as "stable".

I am closing this issue, and please continue to discuss/provide feedback on https://github.com/WindowTop/WindowTop-App/issues/313 

if it is not specific to the crop feature, consider replying at https://github.com/WindowTop/WindowTop-App/issues/304
